
# Site settings
title: Jiali Zhang
name: Jiali Zhang
subtitle:  MAT
email: jiali.zhang@qmul.ac.uk
description: >
   MAT
baseurl: ""
url: "https://jializhangsunny.github.io/"
github_username:  jializhangsunny
disqus_baseurl: "https://jializhangsunny.github.io/"
disqus_shortname: https-jializhangsunny-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Jiali ZHANG"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: jializhangsunny
    url: https://github.com/jializhangsunny
    desc: Fork me on GitHub
    share: false

